FROM mongo
ARG ADMIN_USERNAME
ARG ADMIN_PASSWORD

ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV MONGO_INITDB_ROOT_USERNAME ${ADMIN_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD ${ADMIN_PASSWORD}
ENV MONGO_INITDB_DATABASE admin

ENV MONGO_USERNAME ${DATABASE_USERNAME}
ENV MONGO_PASSWORD ${DATABASE_PASSWORD}

COPY setup.sh /docker-entrypoint-initdb.d/
COPY ["restaurant_data.json", "restaurant_data.json"]
