echo Bulk loading athena data...
mongoimport --db demo --collection restaurants --file restaurant_data.json

echo Creating database user...
mongo athena --eval "db.createUser({'user': '$MONGO_USERNAME', 'pwd': '$MONGO_PASSWORD', 'roles': [{'role': 'read', 'db':'athena'}]})"
